version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # If your `pyproject.toml` is at the root
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "development"
