name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Sync dependencies (locked)
        run: uv sync --locked --all-extras --dev

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check src/formatify

      - name: Run tests with pytest
        run: uv run pytest --tb=short --disable-warnings --cov=src/formatify --cov-report=term-missing
