name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.x'
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --locked --all-extras

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check
          src: src/formatify

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
